Repository teamSixmen/E.O.O_example, pull requests merged in 2024-03, with the labels that each got.

#12 직원호출 완료
  public/images/직원아이콘.png
  src/App.js
  src/pages/Help.js
  src/pages/Style.module.css
Labels: enhancement

#6 [feature_development_timer]kwon
  src/components/Timer.js
  src/pages/Receipt.js
Labels: enhancement

#13 feature_menu_popup_kwon
  src/components/AddBlock.js
  src/components/AddBlock.module.css
  src/components/MenuBlock.js
  src/components/Modal.js
  src/components/Modal.module.css
  src/components/Set.js
  src/components/Set.module.css
Labels: bug

#36 #19 없는 메뉴 노출되지 않게 변경 + etc.
  src/components/MenuBlock.module.css
  src/components/Set.js
  src/data/drink.json
  src/pages/BurgerMenus.js
  src/pages/ChickenMenus.js
  src/pages/DrinkMenus.js
  src/pages/Menus.module.css
  src/pages/SetMenus.js
  src/pages/SideMenus.js
Labels: documentation
